language: python
python:
- '3.7'
stages:
- test
- name: answers
  if: branch = master
jobs:
  include:
  - stage: test
    install:
    - pipenv install --dev --ignore-pipfile --deploy
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    script: pytest --cov-report xml --cov-report term
    after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - stage: answers
    script:
    - python app.py
env:
  global:
  - secure: LJJcK3/SCNsIACQIBiTK5c5Iqo4c0QYdR1YCqBH8rqre+Q4IRJc1NOaREd77nGcl3jSyFGcmCkb8sR7S6anoQndHQxbJsELbM+46tmb6iaVKjxG7cbc74Q/gUrF4wHcOCBhIYePsOs/hNcK9qVUm9LlBfFsgt622uCLwV+anXV27BSmYyr12CZVjGcHSdZpHl9l0Bmyp/ht7bKIQTN2Qgsia2pMEXw3GZp/NDXdCK9IRmMxv/tSntdSeqt13xDYRoctCKZY8YnF3/W9zkvEzVFfJB8+CY9ZzCnO5znR1AU9Vrw749PWbCF8Lo+1t//an2VTfLTCXObHxGuNvbQeKU3QRY+30xXkb4BW3M5M7/Nvh48iMuS5qU47J0HsHbfH66WWxBl520t2aXRciNBx7kA97mRNYVZkoji6541q8YGMIl+QdqydaU/erpwz0/yXSQXXUSJAKIfOfQ5/fNqMSjK6wpcjWMLZC8jxnz2vc69WSbVtuwgvujtsKlaliun9p1aSfRIFgcuwgEmJOxMRRmeXQ3nrvP7bbDVpO00bp7KbSbSurXAUn4CNfT4F80qxCl9KiMnUWV9O6rex5LrSzZOxkbe3nEQ02SNesGGmBUW3N7ZefupBJOIAFQ5ND05F5nmdz5GDijy1BegCb7loYiwlJhL9g3YdJNpk7GL1Sz4U=
  - secure: R0SZaAy/+0Cf9bkhKawG904JUahRKFPdXAL2R06mB0xVTRXaxqf8JVUalMnF+Skg9wogXw3SnONV/znyWYX8Dl6bIiHItFE5loOPCZ4VxlIi9UjUNacTdZ98ZxNzoP5V7APIJhUO0SajyJGK4sLH2gM6LQQV4hNri9QSUXJ1B8kIGnsFKpEVC0vihwhwDKz7DSyyoWFpo899PI+XR41z7ez8E9AasDPMk3cBRFRqIOa84ZAuoSYZ6dtVARpRqETqg1JHA9xlXKiuy5uSITUzXOCEQeZ3EtN20fnPHMNHvUC2cW4RnjUv7JO4c4XuCEdMW4LKjFZCQ4nqo7J5u/e7bvR9L5LKMBi0gxnyHuRBsQ/XcpXFO9ZUZb+jUvkihMUeqU8eILvl/tsq+0xkRiI/knX5KrWuyeJ2dgSM2RiuoKcRBjdp92KTiK+G6DWducWiwlO1i591uYbz75s/UfErwFNYfBGIf/rdZFZMGSf1Neh9/w1Zz0jP33E0ydTaoG0sjRhBM9Ef0aqzlEvrkGxiKM2mIjMbskftX50TZX3eBRra8w8+80BvtGqsfCVI+c/u7bRM9zcWrDxa5+BiAN6Z4WtR22tg/YN+oZRfeMEd0fMTPq6qIn8BMXDzLzE5vT0SxJqZYBWahs5hSE9zK8pstskAwpLbQlLCKZ93D6miWYo=
  - secure: k2LCnCXfnL2iF8NuyoeLF4HprZASsoBHC+Azg4YpQUMmgZI4rI7JCoDAyWJiMwUO7LXSUF5mmZVFuAPHh4NJfj4JS5Oj7xfKQ8bnvBxrPiaSxHkqvY7LmKjU5s87kYmdOj/+m/EPQtsp32lLf0Aa0W+colneUukt/X3VFWQKhrxdy9EzXe9ERpOEdkcRxqCfLmfVUJLHB/MHMghPY2KMINhf4Ju/Bze47iTsXVGo7v0XkWIu3MxjJODub9NBBKPg+5PhZ+5TVdTgVk8ge7podtWukfKMg/b0X43WcIdznFGvSm8ytW1NvmctZaJ/tHDht7lTWxGtMngfJLd612Qd+0wQt3etTpakOQBAPldw2EU4WOw4OYjrOQ7Fru47WPV8yKKz5LI9hwZBVdq1gAuup2k+LptVGvc9L31zMp5+uUxBehNMdHPX6Yp9brr4/djq4+zObegnpVfZseuP0059fldMFKDP5kqfZEAeG+ocKmwe68wH/4YhpEYgSDdTxp/Qly0EHrq84SdBTaQeBmSGHT7kOkEylRXvTpdiBwm4uHwPdqgQII5820WlUg6wXZYAYwrIkoONn/kpRAiwxgQDz9w7oT0NyNw1HNJG+CDguAqnUQzo+I0vOxSjJvIVp4TgmkobcnT64v4YUTPg8QYwaoViCF/IV2K/3MBiTJizBoo=
