env:
  global:
    - CC_TEST_REPORTER_ID=58d3f6495835a1c19f264e739e7034c7da3f2154f730164ae990327cc762c064


language: python
dist: xenial
python:
  - 3.7

stages:
  - test
  - name: answers
    if: branch = master

jobs:
  include:
    - stage: test
      install:
        - pipenv install --dev --deploy #--ignore-pipfile
      before_script: # code coverage tool
         - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
         - chmod +x ./cc-test-reporter
         - ./cc-test-reporter before-build
      script: pytest --cov-report xml:coverage.xml --cov=test_app --cov-report term
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: answers
      script:
        - python app.py
