language: python
python:
- '3.7'
stages:
- test
- name: answers
  if: branch = master
jobs:
  include:
  - stage: test
    install:
    - pipenv install --dev --ignore-pipfile --deploy
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script: pytest --cov-report xml --cov-report term
    after_script:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
  - stage: answers
    script:
    - python app.py
env:
  global:
    secure: LJJcK3/SCNsIACQIBiTK5c5Iqo4c0QYdR1YCqBH8rqre+Q4IRJc1NOaREd77nGcl3jSyFGcmCkb8sR7S6anoQndHQxbJsELbM+46tmb6iaVKjxG7cbc74Q/gUrF4wHcOCBhIYePsOs/hNcK9qVUm9LlBfFsgt622uCLwV+anXV27BSmYyr12CZVjGcHSdZpHl9l0Bmyp/ht7bKIQTN2Qgsia2pMEXw3GZp/NDXdCK9IRmMxv/tSntdSeqt13xDYRoctCKZY8YnF3/W9zkvEzVFfJB8+CY9ZzCnO5znR1AU9Vrw749PWbCF8Lo+1t//an2VTfLTCXObHxGuNvbQeKU3QRY+30xXkb4BW3M5M7/Nvh48iMuS5qU47J0HsHbfH66WWxBl520t2aXRciNBx7kA97mRNYVZkoji6541q8YGMIl+QdqydaU/erpwz0/yXSQXXUSJAKIfOfQ5/fNqMSjK6wpcjWMLZC8jxnz2vc69WSbVtuwgvujtsKlaliun9p1aSfRIFgcuwgEmJOxMRRmeXQ3nrvP7bbDVpO00bp7KbSbSurXAUn4CNfT4F80qxCl9KiMnUWV9O6rex5LrSzZOxkbe3nEQ02SNesGGmBUW3N7ZefupBJOIAFQ5ND05F5nmdz5GDijy1BegCb7loYiwlJhL9g3YdJNpk7GL1Sz4U=
